### PR TITLE
[FSDE-1363] new release 5.2.1

### PR DESCRIPTION
**Pull request by julianatienza**

### CODE REVIEW

**Comment by julianatienza** [comment]
The CI pipeline run successfully in https://jenkinsprod.corp.intranet:8443/job/UX-CHI/job/Playpen/job/ChiGCR/job/ChiGCR/job/PR-36/2/. :white_check_mark:

**Comment by julianatienza** [comment]
Please, can you do a peer review?

**Review by ansonlumen — APPROVED** [review]
It is ok for me

**Review by jfranciscohernbal — APPROVED** [review]
Looks good!

**Review by jcmendez-guerrero — APPROVED** [review]
All fine

**Pull request merged**
